server:
  port: 8877
  servlet:
    session:
      timeout: 60
spring:
  application:
    name: virgo-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yinhaijin/config-repo/
          search-paths: config-repo
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8887/eureka/
