server:
  port: 8090
  servlet:
    session:
      timeout: 60

spring:
  application:
    name: virgo-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yinhaijin/virgo-config
          searchPaths: project-config
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8090/eureka/