server:
  port: 8878
  servlet:
    session:
      timeout: 60

spring:
  application:
    name: virgo-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yinhaijin/virgo-config
          searchPaths: project-config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.108.94:8887/eureka/,http://192.168.108.94:8888/eureka/,http://192.168.108.94:8889/eureka/
