server:
  port: 8080

spring:
  application:
    name: virgo-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yinhaijin/virgo-config
          searchPaths: data